### ISSUE TITLE
您好 有寄信到您的信箱 煩請收信

### ISSUE THREAD

**Issue by benny0523** [ALiangLiang/pchome-api#12]
有程式問題請教...

**Comment by ALiangLiang** [comment]
抱歉我沒收到你的信，有關這個套件的問題可以直接在這裡發問

**Comment by benny0523** [comment]
請問一下，這個套件目前是可以正常運作的嗎？
因為我執行example.js 在加入購物車時沒有正常工作

**Comment by SteinsLaw** [comment]
剛剛路過幫忙測試了一下 可以哦 加入購物車是正常的

**Comment by ALiangLiang** [comment]
我有設置 CI 每天測試加入購物車是否正常，目前來看是可以運作的。你看一下你是不是在設定 Cookie 時有問題。
