### ISSUE TITLE
關於 送出訂單 錯誤

### ISSUE THREAD

**Issue by SteinsLaw** [ALiangLiang/pchome-api#14]
最近在使用時 商品能夠正確加入購物車

但是在送出訂單都會出現錯誤代碼 以至於不會直接結帳完成(確定有貨到付款 免運費 等等的條件)

TypeError: Cannot read property 'PK' of undefined
    at API.order (/mnt/d/user profile/Steins.Lin/Downloads/pchome-api-master/pchome-api-master/api/order.js:14:34)
    at <anonymous>TypeError: Cannot read property 'status' of undefined
    at main (/mnt/d/user profile/Steins.Lin/Downloads/pchome-api-master/pchome-api-master/example.js:33:14)
    at <anonymous>

想請問 突然的變化是哪裡我設定錯誤了嗎

**Comment by ALiangLiang** [comment]
> 最近在使用時 商品能夠正確加入購物車
> 
> 但是在送出訂單都會出現錯誤代碼 以至於不會直接結帳完成(確定有貨到付款 免運費 等等的條件)
> 
> TypeError: Cannot read property 'PK' of undefined
> at API.order (/mnt/d/user profile/Steins.Lin/Downloads/pchome-api-master/pchome-api-master/api/order.js:14:34)
> at TypeError: Cannot read property 'status' of undefined
> at main (/mnt/d/user profile/Steins.Lin/Downloads/pchome-api-master/pchome-api-master/example.js:33:14)
> at
> 
> 想請問 突然的變化是哪裡我設定錯誤了嗎

你有設定Cookie嗎？

**Comment by SteinsLaw** [comment]
有的

是除了Config.json之外 還有哪邊需要特別修改的嗎?

**Comment by Rayman0226** [comment]
我也遇到一模一樣的問題
TypeError: Cannot read property 'PK' of undefined
    at API.order (C:\Users\user\Desktop\pchome-api-master\api\order.js:14:34)
    at async main (C:\Users\user\Desktop\pchome-api-master\example.js:28:18)
TypeError: Cannot read property 'status' of undefined
    at main (C:\Users\user\Desktop\pchome-api-master\example.js:39:14)

**Comment by Rayman0226** [comment]
購物車也有成功加入

**Comment by ALiangLiang** [comment]
你們有動到 `api/` 底下的 code 嗎？

**Comment by sleepyknife** [comment]
同樣的issue，僅能將商品加入至購物車，然後同樣的錯誤訊息
這邊僅有修改過config.json 按照cookie輸入
其餘的source code並沒有修改

node version v14.11.0

**Comment by ALiangLiang** [comment]
應該是修好了，Pchome的API有換過，測試過可以正確送出訂單。
