### ISSUE TITLE
其他付款方式

### ISSUE THREAD

**Issue by askali** [ALiangLiang/pchome-api#18]
其他付款方式有需要做其他處理嗎??

**Comment by ALiangLiang** [comment]
有，你是要用到哪種付款方式？

**Comment by askali** [comment]
ATM或是ibon

**Comment by ALiangLiang** [comment]
已支援

https://github.com/ALiangLiang/pchome-api/commit/3543359a60d5a7c2f876e9d3f7bdc0841fa150e3
