### ISSUE TITLE
第三方支付的可能性

### ISSUE THREAD

**Issue by chickkenc** [ALiangLiang/pchome-api#19]
將使用者的信用卡資訊儲存起來似乎不太對
要在程式邏輯上替使用者完成"信用卡"付款的流程似乎也不符合安全考量
所以想詢問，這隻程式，是否有可能可以支援其他的第三方支付
例如LINE PAY 或街口支付等等...替使用者完成結帳前的所有流程，最後在跳出付款頁面讓使用者進行掃條碼結帳

**Comment by ALiangLiang** [comment]
@chickkenc  可以吧，建議就是得寫成桌面應用程式，才能夠彈出第三支付的跳轉頁面來完成付款，否則純 CLI 做起來應該有點麻煩。

**Comment by chickkenc** [comment]
好的，明白，另外想詢問作者大大....
感覺好像只能直接送單進行測試，或者作者大大都用什麼方式進行測試的呢?
頻繁發送訂單然後在取消，有可能被BAN掉嗎?或者帳號被封之類的?

**Comment by ALiangLiang** [comment]
我就是直接送單測試啊，訂單完成就是成功，然後馬上退訂，當然盡量不要送出一堆訂單造成困擾，然後 PChome
那邊我也不確定會怎麼處理，所以成功過的話就別繼續送了。

Jax <notifications@github.com> 於 2020年12月21日 週一 10:23 寫道：

**Comment by chickkenc** [comment]
好的，明白了，感謝作者大大
