### ISSUE TITLE
error code 325

### ISSUE THREAD

**Issue by chickkenc** [ALiangLiang/pchome-api#20]
測試了幾張單之後，現在送單會出現error
{"status":"ERR","code":325,"msg":"下單限制","act":"L","url":"https:\\/\\/ecssl.pchome.com.tw\\/sys\\/cflow\\/fsindex\\/errPage\\/325","usePostMsg":"N"}'

作者大大有遇到這個問題嗎?是否是今日送單量已經過多?或者該檢查什麼參數?

**Comment by ALiangLiang** [comment]
沒遇過，看訊息有可能是吧。

Jax <notifications@github.com> 於 2020年12月21日 週一 15:51 寫道：

**Comment by askali** [comment]
我測試太過密集會出現這個訊息...加入購物車跟結帳中間加一個sleep 3~5秒 就會成功

**Comment by eddielin1223** [comment]
請問有支援整點搶購嗎? 好像都會被擋住耶

**Comment by ALiangLiang** [comment]
> 請問有支援整點搶購嗎? 好像都會被擋住耶

這我沒測過，如果有問題你可以提供錯誤訊息跟重現流程，並且開新的一篇 issue 嗎？
