### ISSUE TITLE
是不是能在order.js各種encrypt/key/token加解密上加註解

### ISSUE THREAD

**Issue by lukedoomer** [ALiangLiang/pchome-api#23]
雖然能實際跑javascript 但不懂為什麼要encrypt(random())
請問大大下單方法是重現電腦版還是手機版做出來的?
學習求教 謝謝

**Comment by ALiangLiang** [comment]
重現電腦版的，我的理解應該是隨機產生一組密碼、金鑰，用來加密其他資訊用的，看之後的程式碼，會發現這組密碼會被 PK 加密後一起送到伺服器來解密。

**Comment by lukedoomer** [comment]
既然密碼和金鑰是隨機的，是不是我也可以寫死或自行亂定義，反正都要當成參數送去伺服器解密？

**Comment by ALiangLiang** [comment]
我沒嘗試過，或許可以，就看你要不要省下微小的運算時間。

lukedoomer <notifications@github.com> 於 2021年1月5日 週二 下午5:07寫道：
