### ISSUE TITLE
order.js 中 'res.PK' 未定義問題

### ISSUE THREAD

**Issue by kuroneko306** [ALiangLiang/pchome-api#25]
您好 :

剛才試著自己執行修改過後的example.js
結果出現以下的錯誤訊息：

> TypeError: Cannot read property 'PK' of undefined
>  at API.order (...\api\order.js:14:34)
>  at async main (...\example.js:39:18)

在\api\order.js 中Line 8 的 res 沒有定義 'PK'
但是Line 14 要求存取 res.PK
請問這裡的'PK'值是作為什麼用途以及如何取得 ?

謝謝

**Comment by ALiangLiang** [comment]
那段錯誤訊息的意思是：`res 為 undefined 而此變數並無 PK 屬性`，大概是你 res 未定義或未賦值。
