### ISSUE TITLE
如何解決 OrderSubmit 後得到 recaptcha 0003 or recaptcha 0005 的問題？

### ISSUE THREAD

**Issue by mong0520** [ALiangLiang/pchome-api#34]
hi @ALiangLiang , 

不確定這個 repo 是否還在維護，最近發現這個 repo 並且試了一下，成功率大概30%，高機率被下單限制或是中 recaptcha。
下單限制可以靠 sleep 解決，想請問您是怎麼解決 recaptcha 的問題呢？
以下是中 reCaptcha 的 response
```json
{
  "status": "ERR",
  "code": 329,
  "msg": "recaptcha 0003",
  "line": 97,
  "act": "L",
  "url": "https://ecssl.pchome.com.tw/sys/cflow/fsindex/errPage/329",
  "usePostMsg": "N"
}
```

```json
{
  "status": "ERR",
  "code": 666,
  "msg": "recaptcha 0005",
  "line": 112,
  "act": "",
  "usePostMsg": "N"
}
```

**Comment by ALiangLiang** [comment]
跟這個 [issue](https://github.com/ALiangLiang/pchome-api/issues/22) 一樣，似乎兩年多前就這樣了，而我這專案那時 PCHome 還沒有用上 recaptcha，現在遇到 recaptcha 我覺得除非有 bug 可以 bypass，不然我覺得也只能這樣，而有 bug 的機率我認為偏低，所以我應該不會去處理這塊了。

Duplicate of #22

**Comment by mong0520** [comment]
好的，因為我自己實作 python 版的有碰到此問題，想說來咨詢一下有沒有解法, thanks!
