### ISSUE TITLE
About api

### ISSUE THREAD

**Issue by petertsai0224** [ALiangLiang/pchome-api#4]
請問目前這隻API還可以使用嗎?
因為感覺PCHOME API好像有些不能在使用了?
目前在剛研究Node js剛好需要用到PCHOME結帳
因此想順便問可以簡單說明一下使用方式嗎
剩下我在自己摸索看看
謝謝

**Comment by ALiangLiang** [comment]
不曉得，你可以試試看，裡頭有 `test.js` 檔案，稍微改一下參數執行看看。我也是手工搶完switch才想起來我有做過這個專案哈哈哈哈哈

petertsai0224 <notifications@github.com> 於 2020年5月1日 週五 15:05 寫道：

**Comment by petertsai0224** [comment]
我也是今天SWITCH搶失敗才想說有沒有其他方式看看哈哈哈
不過我沒試過Node js 想嘗試改成C#看看
因為我直接下node test.js會顯示我缺少config
只是config內部不太確定要怎麼寫

**Comment by ALiangLiang** [comment]
哦我沒有推範例設定檔 `config.json` 上去，
裡面應該只是帳號密碼而已，
`account` 與 `pwd`
試試看
```json
{"account": "<帳號>", "pwd": "<密碼>"}
```

**Comment by petertsai0224** [comment]
感謝 不過這問題我後來直接又遇到點問題還在解決

< SyntaxError: Unexpected end of JSON input
<     at JSON.parse (<anonymous>)
<     at API.getCartInfo (D:\nojs\pchome-api-master\api\getCartInfo.js:9:15)
<     at <anonymous>

**Comment by ALiangLiang** [comment]
目前更新了，確定可以用

**Comment by exriesz** [comment]
請問目前這隻api還能用嗎?
